auth_uri: https://accounts.google.com/o/oauth2/auth
client_secret: '-8ZoaOSBXaU7LtnVDXpcnNmZ'
token_uri: https://accounts.google.com/o/oauth2/token
client_email: 642409960651-4v90rfvpdcgo0qmdj023oo7pb7js20d1.apps.googleusercontent.com
redirect_uri: "http://localhost:3000"
client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/642409960651-4v90rfvpdcgo0qmdj023oo7pb7js20d1@developer.gserviceaccount.com
client_id: 642409960651-4v90rfvpdcgo0qmdj023oo7pb7js20d1.apps.googleusercontent.com
auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs

